---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frauddetection
  labels:
    app: frauddectection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frauddetection
  template:
    metadata:
      labels:
        app: frauddetection
    spec:
      containers:
        - name: sotoseven
          image: docker.io/alexsotoharness/sotoseven:latest
          ports:
            - containerPort: 8080
