---
apiVersion: v1
kind: Service
metadata:
  name: frauddetection-service
spec:
  selector:
    app: frauddetection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
